//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobanlarMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addresses
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string title { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string postal_code { get; set; }
        public string landmark { get; set; }
        public string phone_number { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string district { get; set; }
        public string quarter { get; set; }
    
        public virtual users users { get; set; }
    }
}
