//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobanlarMarket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public categories()
        {
            this.coupon_categories = new HashSet<coupon_categories>();
            this.sub_categories = new HashSet<sub_categories>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Kategori adý gereklidir")]
        [StringLength(30, ErrorMessage = "Kategori adý en fazla 30 karakter olmalýdýr")]
        public string name { get; set; }

        [Required(ErrorMessage = "Kategori görseli gereklidir")]
        public string cover { get; set; }

        [StringLength(50, ErrorMessage = "Açýklama en fazla 50 karakter olmalýdýr")]
        public string description { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coupon_categories> coupon_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_categories> sub_categories { get; set; }
    }
}
