//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobanlarMarket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class company_details
    {
        public int id { get; set; }
        public string name { get; set; }
        [Required(ErrorMessage = "Bu alan gereklidir.")]

        public Nullable<decimal> shipping_cost { get; set; }
        [Required(ErrorMessage = "Teslimat ücreti alaný gereklidir.")]

        public Nullable<decimal> min_amonunt_for_free_shipping { get; set; }
        public string homepage_top_text { get; set; }
        public string homepage_slider_title { get; set; }
        public string homepage_slider_text { get; set; }
        public string homepage_slider_img { get; set; }
        public string homepage_slider_link { get; set; }
        public string homepage_bottom_header { get; set; }
        public string homepage_bottom_text { get; set; }
        public string homepage_bottom_img { get; set; }
        public string homepage_bottom_link { get; set; }
    }
}
