//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobanlarMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon_products
    {
        public int id { get; set; }
        public int coupon_id { get; set; }
        public int product_id { get; set; }
    
        public virtual coupons coupons { get; set; }
        public virtual products products { get; set; }
    }
}
