//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobanlarMarket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class coupons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coupons()
        {
            this.cart = new HashSet<cart>();
            this.coupon_categories = new HashSet<coupon_categories>();
            this.coupon_products = new HashSet<coupon_products>();
            this.order_details = new HashSet<order_details>();
            this.payment_details = new HashSet<payment_details>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Kupon kodu gereklidir")]
        [StringLength(20, ErrorMessage = "Kupon kodu en fazla 20 karakter olmalýdýr")]
        public string Code { get; set; }

        [Required(ErrorMessage = "Ýndirim türü gereklidir")]
        public string DiscountType { get; set; }

        [Required(ErrorMessage = "Ýndirim miktarý gereklidir")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Ýndirim miktarý sýfýrdan büyük olmalýdýr")]
        public decimal DiscountValue { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "Minimum harcama sýfýrdan küçük olamaz")]
        public decimal? MinimumSpend { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "Maksimum indirim miktarý sýfýrdan küçük olamaz")]
        public decimal? MaxDiscountAmount { get; set; }

        [Required(ErrorMessage = "Baþlangýç tarihi gereklidir")]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessage = "Bitiþ tarihi gereklidir")]
        public DateTime EndDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coupon_categories> coupon_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coupon_products> coupon_products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_details> payment_details { get; set; }
    }
}
