//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobanlarMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public Nullable<bool> is_read { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> order_id { get; set; }
    
        public virtual users users { get; set; }
    }
}
