//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobanlarMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_details()
        {
            this.order_item = new HashSet<order_item>();
            this.payment_details = new HashSet<payment_details>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> coupon_id { get; set; }
        public Nullable<int> address_id { get; set; }
        public string shipping_address { get; set; }
        public string shipping_title { get; set; }
        public string shipping_city { get; set; }
        public string shipping_country { get; set; }
        public string shipping_name { get; set; }
        public string shipping_surname { get; set; }
        public string shipping_phone_number { get; set; }
        public string shipping_postal_code { get; set; }
        public Nullable<bool> is_delivered { get; set; }
    
        public virtual coupons coupons { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_details> payment_details { get; set; }
    }
}
