//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobanlarMarket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.campaign_products = new HashSet<campaign_products>();
            this.coupon_products = new HashSet<coupon_products>();
            this.order_item = new HashSet<order_item>();
            this.product_images = new HashSet<product_images>();
            this.products_skus = new HashSet<products_skus>();
            this.wishlist = new HashSet<wishlist>();
            this.cart_item = new HashSet<cart_item>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Ürün adý gereklidir")]
        [StringLength(50, ErrorMessage = "Ürün adý en fazla 50 karakter olmalýdýr")]
        [MinLength(2,ErrorMessage ="Ürün adý en az 2 karakterden oluþmalýdýr")]
        public string name { get; set; }

        [StringLength(500, ErrorMessage = "Açýklama en fazla 500 karakter olmalýdýr")]
        public string description { get; set; }

        public string summary { get; set; }

        public string cover { get; set; }
        public Nullable<int> subcategory_id { get; set; }
        public int? subcategory { get; set; }

        public string sub_subcategory_id { get; set; } 

        [Range(0, 2, ErrorMessage = "Kategori tipi 0, 1 veya 2 olmalýdýr")]
        public int? category_type { get; set; }

        public DateTime? created_at { get; set; }

        public DateTime? deleted_at { get; set; }
    
    public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campaign_products> campaign_products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coupon_products> coupon_products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_images> product_images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products_skus> products_skus { get; set; }
        public virtual sub_categories sub_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wishlist> wishlist { get; set; }
        public virtual sub_subcategories sub_subcategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart_item> cart_item { get; set; }
    }
}
